# Generated by Django 3.0.4 on 2020-03-23 09:17

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('finish', models.TimeField(verbose_name='Конец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'рабочий день',
                'verbose_name_plural': 'рабочие дни',
                'ordering': ('day', 'start', 'finish'),
            },
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='timetracker.Project', verbose_name='Проект')),
                ('users', models.ManyToManyField(blank=True, db_index=True, related_name='subsystems', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'подсистема',
                'verbose_name_plural': 'подсистемы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Название')),
                ('users', models.ManyToManyField(blank=True, db_index=True, related_name='sectors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направления',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='timetracker.Sector', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('time', models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=57600))], verbose_name='Длительность')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='timetracker.Subsystem', verbose_name='Подсистема')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='timetracker.WorkDay', verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'деятельность',
                'verbose_name_plural': 'деятельности',
                'ordering': ('work_day__day', 'time', 'created_at'),
            },
        ),
    ]
